name: JPG Mover


on:
  push:
    paths:
      '**.jpg'
  
  pull_request:
    paths:
      '**.jpg'

permissions:
  contents: write

jobs:
  move-jpg:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4.1.2

      - name: Move .jpg files
        run: mv *.jpg Images/

      - name: Commit changes
        run: |
          git config --global user.name "DanielBrett"
          git config --global user.email "dbrett@brocku.ca"
          git add .
          git commit -m "JPG Mover Activated!"
          git push
